`{r} translations$headerList$createdAt`:

:   `{r} format(Sys.time(), format = "%x %X", tz = "UTC", usetz = TRUE)`

`{r} translations$headerList$analysisPeriod`:

:   `{r} paste(format(reportingPeriodFrom, format = "%x"), format(reportingPeriodTo, format = "%x"), sep = " - ")`

`{r} if(nrow(countries) > 1){translations$headerList$countries}else{translations$headerList$country}`:

:   `{r} paste(countries |> arrange(displayName) |> pull(displayName), sep = ", ")`

`{r} translations$headerList$birthweightFilter`:

:   `{r} if(birthWeightFrom == 0L && birthWeightTo == 2147483647L) translations$headerList$allBirthweights else paste(label_bw(birthWeightFrom), label_bw(birthWeightTo), sep = " - ")`

`{r} translations$headerList$gestationalAgeFilter`:

:   `{r} if(gestationalAgeFrom == 0L && gestationalAgeTo == 2147483647L) translations$headerList$allGestationalAges else paste0(format_ga(c(gestationalAgeFrom, gestationalAgeTo)), collapse = " - ")`

```{r Countries hint}
#| echo: false
#| output: asis

if(nrow(countries) > 1){
  cat(sep = "\n", c(
    "::: {.callout-note}",
    paste0("## ", translations$headerList$multiCountryHintHeader),
    "",
    translations$headerList$multiCountryHint,
    "",
    translations$headerList$multiCountryHintGoal,
    ":::"))
} else {
  cat(sep = "\n", c(
    "::: {.callout-note}",
    paste0("## ", translations$headerList$singleCountryHintHeader),
    "",
    translations$headerList$singleCountryHint,
    "",
    translations$headerList$singleCountryRepresentativenessHint,
    ":::"))
}
```

```{r Custom report hint}
#| echo: false
#| output: asis

if(!testUnitFilter || !defaultPatientFilter){
  cat(sep = "\n", c("::: {.callout-note}", paste0(
    c(
    translations$headerList$specialAnalysisHint,
    if(!testUnitFilter){
      paste0(translations$headerList$includesTestDepartments,
      if(!defaultPatientFilter)
        translations$headerList$and
      else
        ".", collapse = "")
    },
    if (!defaultPatientFilter)
      translations$headerList$ignoresInclusionCriteria
    ), collapse = " "),
    ":::"))
}
```
