```{r General setup and parameter preparation, message=FALSE, warning=FALSE}
#| include: false
suppressMessages(pak::pak("Brar/neoipcr@TowardsReferenceReport"))
suppressMessages(library(tidyverse, warn.conflicts = FALSE, quietly = TRUE))
suppressMessages(library(smplot2, warn.conflicts = FALSE, quietly = TRUE))
suppressMessages(library(scales, warn.conflicts = FALSE, quietly = TRUE))
suppressMessages(library(patchwork, warn.conflicts = FALSE, quietly = TRUE))
suppressMessages(library(gt, warn.conflicts = FALSE, quietly = TRUE))
suppressMessages(library(neoipcr, warn.conflicts = FALSE, quietly = TRUE))

if(!exists("params")) params <- list()
reportingPeriodFrom <- as_date(coalesce(params[["reportingPeriodFrom"]], "2024-01-01"))
reportingPeriodTo <- as_date(coalesce(params[["reportingPeriodTo"]], Sys.Date()))
birthWeightFrom <- coalesce(params[["birthWeightFrom"]], 0L)
birthWeightTo <- coalesce(params[["birthWeightTo"]], 2147483647L)
gestationalAgeFrom <- coalesce(params[["gestationalAgeFrom"]], 0L)
gestationalAgeTo <- coalesce(params[["gestationalAgeTo"]], 2147483647L)
token <- coalesce(params$token, Sys.getenv("NEOIPC_DHIS2_TOKEN", unset = NA))
session_id <- coalesce(params[["session_id"]], Sys.getenv("NEOIPC_DHIS2_SESSION_ID", unset = NA))
countryFilter = params[["countryFilter"]]
hospitalFilter = params[["hospitalFilter"]]
defaultPatientFilter = coalesce(params[["defaultPatientFilter"]], TRUE)
testUnitFilter = coalesce(params[["testUnitFilter"]], TRUE)
language <- dplyr::coalesce(params$language, "en")
default_countries <- list(
  en = "GB",
  de = "DE"
)
country <- dplyr::coalesce(params$country, default_countries[[language]], NA_character_)
codepage <- dplyr::coalesce(params$codepage, "UTF-8")
locale <- paste0(language, (if(is.na(country)) NULL else paste0("_", country)), ".", codepage)
gt_locale <- paste0(language, (if(is.na(country)) NULL else paste0("-", country)))
options(`gt.locale` = gt_locale)
`_locales` <- (gt::info_locales(begins_with = substr(gt_locale,1,1)))$`_data`
locale_sep_mark <- `_locales`$group[`_locales`$locale == gt_locale]
invisible(Sys.setlocale(category = "LC_ALL", locale = locale))
translation_file <- paste0("translations/", stringr::str_extract(locale, "^([^.]+)"),".json")
rm(gt_locale, `_locales`)
```

```{r Importing data}
#| include: false
data <- import_dhis2(dataset_options = dhis2_dataset_options(include_country = "yes", include_department = "yes"))

ichi_health_interventions <- read_csv("../../../Surveillance-Private/metadata/WHO/ICHI/Health interventions.csv", col_names = c("code","intervention","url"), col_types = "ccc")
ichi_targets <- read_csv("../../../Surveillance-Private/metadata/WHO/ICHI/Targets.csv", col_names = c("code","target","url"), col_types = "ccc")

if(file.exists(translation_file)) {
  translations <- readr::read_file(translation_file) |> jsonlite::fromJSON()
} else {
  translation_file <- paste0("translations/",stringr::str_extract(locale, "^([^_]+)"),".json")
  if(file.exists(translation_file)) {
    translations <- readr::read_file(translation_file) |> jsonlite::fromJSON()
  } else {
    rlang::abort(paste0("Failed to find translation file for locale", locale))
  }
}

get_procedure_category <- function(x) {
  target <- stringr::str_extract(x, "^([A-Za-z]{3})\\.", 1)
  action <- stringr::str_extract(x, "^([A-Za-z]{3})\\.([A-Za-z]{2})", 2)
  means <- stringr::str_extract(x, "^([A-Za-z]{3})\\.([A-Za-z]{2})\\.([A-Za-z]{2})", 3)
  dplyr::case_when(
    # Neurosurgery
    ############################################################################
    target %in% c("AAE","MAA") &
      means %in% c("AA","AB") ~ "neurosurgery",

    # Cardiac/large vessel surgery
    ############################################################################
    target == "HIJ" & action == "LA" ~ "cardiac_and_large_vessel_surgery",

    target == "HIK" & means == "AA" ~ "cardiac_and_large_vessel_surgery",

    # Lung/pleural space/thoracic surgery
    ############################################################################
    target == "MCX" & means %in% c("AA","AB") ~ "lung_pleural_space_thoracic_surgery",

    x == "JBF.LL.AA" ~ "lung_pleural_space_thoracic_surgery",

    # Abdominal surgery
    ############################################################################
    target %in% c("KBF","KBK","KBP","KBZ","KMA","PAK","PAL") &
      means %in% c("AA","AB") ~ "abdominal_surgery",

    target %in% c("PTA","PTB") &
      action == "LA" &
      means == "AC" ~ "abdominal_surgery",

    x == "KMA.JB.AE" ~ "abdominal_surgery",

    # Inguinal hernia surgery
    ############################################################################
    x == "PAM.MK.AA" ~ "inguinal_hernia_surgery",

    # Other
    ############################################################################
    x %in% c("IZD.DL.AF","JBA.LI.AA","KAB.FB.AC",
             "PAW.JB.AA") ~ "other",

    x == "BCD.DB.AE" ~ "other",

    # Not considered as surgery (remove)
    ############################################################################
    x %in% c("KBA.LG.AD","KBK.LD.AH","PTB.SN.AC") ~ "not_surgery",

    # To be categorised (default)
    ############################################################################
    .default = "to_be_categorised"
  ) |>
    factor(
      levels = c(
        "abdominal_surgery",
        "neurosurgery",
        "inguinal_hernia_surgery",
        "cardiac_and_large_vessel_surgery",
        "lung_pleural_space_thoracic_surgery",
        "other",
        "not_surgery",
        "to_be_categorised"))
}

department_with_enrollment_keys <- data$enrollments |>
  dplyr::pull(department_key) |>
  unique() |>
  sort()

n_departments_with_enrollments <- length(department_with_enrollment_keys)

surgical_department_keys <- data$enrollments |>
  dplyr::semi_join(
    data$events |>
      dplyr::filter(event_type_key == "pro"),
    dplyr::join_by(enrollment_key)) |>
  dplyr::pull(department_key) |>
  unique() |>
  sort()

n_surgical_departments <- length(surgical_department_keys)

n_enrolled_patients = data$enrollments$patient_key |>
  unique() |>
  length()

department_patients <- data$enrollments |>
  dplyr::group_by(department_key) |>
  dplyr::summarise(
    n_patients = dplyr::n_distinct(patient_key),
    n_enrollments = dplyr::n())

n_procedures_per_patient <- data$events |>
  dplyr::inner_join(data$surgeryData, dplyr::join_by(event_key)) |>
  dplyr::summarise(n_patients = n_distinct(patient_key), n_procedures = n()) |>
  dplyr::mutate(procedures_per_patient = n_procedures / n_patients) |>
  dplyr::pull(procedures_per_patient)

get_AWaRe_days <- function()
{
  data$substanceDays |>
    dplyr::group_by(.data$event_key, .data$substance_code) |>
    dplyr::summarise(days = sum(days), .groups = "drop") |>
    dplyr::inner_join(
      data$metadata$antimicrobialSubstances |>
        dplyr::mutate(
          AWaRe = factor(
            tolower(
              stringr::str_extract(
                .data$WHO_AWARE,
                "^WHO_AWARE_(A|W|R).+$",
                group = 1)),
            levels = c("a","w","r"))) |>
        dplyr::select(code, AWaRe),
      dplyr::join_by("substance_code" == "code")) |>
    dplyr::group_by(event_key, AWaRe) |>
    dplyr::summarise(days = sum(days), .groups = "drop") |>
    tidyr::pivot_wider(
      names_from = AWaRe,
      values_from = days,
      names_glue = "{AWaRe}_{.value}",
      values_fill = 0L)
}

AWaReDays <- get_AWaRe_days()

risk_time <- data$surveillanceEndData |>
  dplyr::inner_join(AWaReDays, dplyr::join_by(event_key)) |>
  dplyr::reframe(
    across(
      tidyselect::ends_with("_days"),
      sum)) |>
  dplyr::mutate(
    across(
      !"patient_days",
      ~ .x / .data$patient_days * 100,
      .names = "{.col}_rate")) |>
  dplyr::rename_with(~ stringr::str_remove_all(.x, "days_"))

department_risk_time <- data$surveillanceEndData |>
  dplyr::inner_join(AWaReDays, dplyr::join_by(event_key)) |>
  dplyr::inner_join(
    data$events |>
      dplyr::select("event_key","enrollment_key"),
    dplyr::join_by("event_key")) |>
  dplyr::inner_join(
    data$enrollments |>
      dplyr::select("enrollment_key","department_key"),
    dplyr::join_by("enrollment_key")) |>
  dplyr::group_by(.data$department_key) |>
  dplyr::summarise(across(tidyselect::ends_with("_days"), sum)) |>
  dplyr::mutate(
    across(
      !c("department_key","patient_days"),
      ~ .x / .data$patient_days * 100,
      .names = "{.col}_rate")) |>
  dplyr::rename_with(~ stringr::str_remove_all(.x, "days_"))

risk_rate_quartiles <- department_risk_time |> select(tidyselect::ends_with("_rate")) |> reframe(across(everything(), ~quantile(.x, prob = c(.25,.5,.75))))

table_usage_density_rate <- risk_time |>
  dplyr::select(!"patient_days" & tidyselect::ends_with("_days")) |>
  pivot_longer(
    cols = tidyselect::ends_with("_days"),
    values_to = "Usage days") |>
  dplyr::mutate(
    Factor = .data$name,
    .before = 1,
    .keep = "unused") |>
  dplyr::bind_cols(
    risk_time |>
      dplyr::select(tidyselect::ends_with("_rate")) |>
      tidyr::pivot_longer(
        cols = tidyselect::ends_with("_rate"),
        values_to = "Pooled mean")) |>
  dplyr::bind_cols(
    risk_rate_quartiles |>
      dplyr::bind_cols(tibble::tibble(name = c("q1","q2","q3"))) |>
      tidyr::pivot_wider(
        values_from = tidyselect::ends_with("_rate")) |>
      tidyr::pivot_longer(
        tidyselect::everything(),
        names_pattern = "^(.+)_(q(?:1|2|3))$",
        names_to = c("rate",".value"))) |>
  dplyr::select(!tidyselect::all_of(c("name","rate"))) |>
  dplyr::mutate(
    Factor = factor(
      stringr::str_extract(.data$Factor,"^(.+)_days", 1),
      levels = c("cvc","pvc","vs","inv","niv","human_milk","probiotic",
                 "kangaroo_care","ab","a","w","r"))) |>
  dplyr::arrange(Factor)

incidence_density_rate_quartiles <- data$events |>
  dplyr::filter(event_type_key %in% c("bsi","nec","hap")) |>
  dplyr::group_by(event_type_key, department_key) |>
  dplyr::summarise(n=n(), .groups = "drop") |>
  tidyr::pivot_wider(
    names_from = event_type_key,
    values_from = n,
    values_fill = 0) |>
  dplyr::mutate(si = bsi + hap) |>
  dplyr::inner_join(
    department_risk_time |>
      select("department_key","patient_days"), join_by("department_key")) |>
  mutate(
    across(
        !c("department_key","patient_days"),
        ~ .x / .data$patient_days * 1000,
        .names = "{.col}_rate")) |>
  select(tidyselect::ends_with("_rate")) |>
  reframe(across(everything(), ~quantile(.x, prob = c(.25,.5,.75)))) |>
  dplyr::bind_cols(tibble::tibble(name = c("q1","q2","q3"))) |>
  tidyr::pivot_wider(values_from = tidyselect::ends_with("_rate")) |>
  tidyr::pivot_longer(
    tidyselect::everything(),
    names_pattern = "^(.+)_(q(?:1|2|3))$",
    names_to = c("rate",".value"))

table_incidence_density_rates <- data$events |>
  dplyr::filter(event_type_key %in% c("bsi","nec","hap")) |>
  dplyr::group_by(event_type_key) |>
  dplyr::summarise(n=n()) |>
  tidyr::pivot_wider(names_from = event_type_key, values_from = n) |>
  dplyr::mutate(si = bsi + hap) |>
  mutate(
    across(
      tidyselect::everything(),
      ~ .x / risk_time$patient_days * 1000,
      .names = "{.col}_Pooled mean")) |>
  dplyr::rename_with(~paste0(.x,"_count"), !tidyselect::contains("_")) |>
  tidyr::pivot_longer(
    cols = tidyselect::everything(),
    names_pattern = "^(.+)_(.+)$",
    names_to = c("infectionType","name")) |>
  tidyr::pivot_wider() |>
  dplyr::inner_join(
    incidence_density_rate_quartiles |>
      mutate(
        infectionType = stringr::str_extract(.data$rate, "^[^_]+"),
        .keep = "unused"),
    dplyr::join_by("infectionType")) |>
  dplyr::mutate(
    Infection = factor(
      .data$infectionType,
      levels = c("si","bsi","hap","nec")),
    `No of infections` = as.integer(.data$count),
    .keep = "unused",
    .before = 1) |>
  dplyr::relocate("Infection") |>
  dplyr::arrange(Infection)

table_device_associated_incidence_density_rates <- data$events |>
  dplyr::inner_join(
    data$sepsisData |>
      dplyr::select("event_key","dev_ass") |>
      dplyr::filter(dev_ass != 0) |>
      dplyr::mutate(
        dev_ass = dplyr::case_match(
          as.integer(as.character(.data$dev_ass)),
          1 ~ "cvc_ass",
          2 ~ "pvc_ass")),
    dplyr::join_by("event_key")) |>
  dplyr::group_by(dev_ass) |>
  dplyr::summarise(n=n()) |>
  tidyr::pivot_wider(
    names_from = dev_ass,
    values_from = n,
    values_fill = 0) |>
  dplyr::mutate(
    cvc_bsi_rate = cvc_ass / risk_time$cvc_days * 1000,
    pvc_bsi_rate = pvc_ass / risk_time$pvc_days * 1000) |>
  tidyr::pivot_longer(
    tidyselect::everything(),
    names_to = c("Infection", "name"),
    names_sep = "_") |>
  tidyr::pivot_wider() |>
  dplyr::mutate(
    Infection = paste0(.data$Infection,"_ass_bsi"),
    `No of dev-ass inf.` = as.integer(ass),
    .keep = "unused",
    .before = 2) |>
  dplyr::rename(`Pooled mean` = bsi) |>
  dplyr::inner_join(
    data$events |>
      dplyr::inner_join(
        data$sepsisData |>
          dplyr::select("event_key","dev_ass") |>
          dplyr::filter(dev_ass != 0) |>
          dplyr::mutate(
            dev_ass = dplyr::case_match(
              as.integer(as.character(.data$dev_ass)),
              1 ~ "cvc_ass",
              2 ~ "pvc_ass")),
        dplyr::join_by("event_key")) |>
      dplyr::group_by(department_key, dev_ass) |>
      dplyr::summarise(n=n(), .groups = "drop") |>
      tidyr::pivot_wider(
        names_from = dev_ass,
        values_from = n,
        values_fill = 0) |>
      dplyr::inner_join(
        department_risk_time |>
          dplyr::select("department_key","cvc_days","pvc_days"),
        dplyr::join_by("department_key")) |>
      dplyr::mutate(
        cvc_ass_bsi = cvc_ass / cvc_days * 1000,
        pvc_ass_bsi = pvc_ass / pvc_days * 1000,
        .keep = "none") |>
      reframe(
        across(everything(), ~quantile(.x, prob = c(.25,.5,.75)))) |>
      dplyr::bind_cols(tibble::tibble(name = c("q1","q2","q3"))) |>
      tidyr::pivot_wider(values_from = tidyselect::ends_with("_bsi")) |>
      tidyr::pivot_longer(
        tidyselect::everything(),
        names_pattern = "^(.+)_(q(?:1|2|3))$",
        names_to = c("Infection",".value")), dplyr::join_by("Infection")) |>
  dplyr::bind_rows(
    data$events |>
      dplyr::inner_join(
        data$pneumoniaData |>
          dplyr::select("event_key","dev_ass") |>
          dplyr::filter(dev_ass != 0) |>
          dplyr::mutate(
            dev_ass = dplyr::case_match(
              as.integer(as.character(.data$dev_ass)),
              1 ~ "niv_ass",
              2 ~ "inv_ass")),
        dplyr::join_by("event_key")) |>
      dplyr::group_by(dev_ass) |>
      dplyr::summarise(n=n()) |>
      tidyr::pivot_wider(
        names_from = dev_ass,
        values_from = n,
        values_fill = 0) |>
      dplyr::mutate(
        vs_ass = niv_ass + inv_ass,
        vs_ass_hap = (niv_ass + inv_ass) / risk_time$vs_days * 1000,
        niv_ass_hap = niv_ass / risk_time$niv_days * 1000,
        inv_ass_hap = inv_ass / risk_time$inv_days * 1000) |>
      tidyr::pivot_longer(
        tidyselect::everything(),
        names_to = c("Infection", "name"),
        names_pattern = "^([^_]+)_(.+)$") |>
      tidyr::pivot_wider() |>
      dplyr::mutate(
        Infection = paste0(.data$Infection,"_ass_hap"),
        `No of dev-ass inf.` = as.integer(ass),
        .keep = "unused",
        .before = 2) |>
      dplyr::rename(`Pooled mean` = ass_hap) |>
      dplyr::inner_join(
        data$events |>
          dplyr::inner_join(
            data$pneumoniaData |>
              dplyr::select("event_key","dev_ass") |>
              dplyr::filter(dev_ass != 0) |>
              dplyr::mutate(
                dev_ass = dplyr::case_match(
                  as.integer(as.character(.data$dev_ass)),
                  1 ~ "niv_ass",
                  2 ~ "inv_ass")),
            dplyr::join_by("event_key")) |>
          dplyr::group_by(department_key, dev_ass) |>
          dplyr::summarise(n=n(), .groups = "drop") |>
          tidyr::pivot_wider(
            names_from = dev_ass,
            values_from = n,
            values_fill = 0) |>
          dplyr::inner_join(
            department_risk_time |>
              dplyr::select("department_key","vs_days","niv_days","inv_days"),
            dplyr::join_by("department_key")) |>
          dplyr::mutate(
            vs_ass_hap = (niv_ass + inv_ass) / vs_days * 1000,
            niv_ass_hap = niv_ass / niv_days * 1000,
            inv_ass_hap = inv_ass / inv_days * 1000, .keep = "none") |>
          reframe(across(everything(), ~quantile(.x, prob = c(.25,.5,.75)))) |>
          dplyr::bind_cols(tibble::tibble(name = c("q1","q2","q3"))) |>
          tidyr::pivot_wider(values_from = tidyselect::ends_with("_hap")) |>
          tidyr::pivot_longer(
            tidyselect::everything(),
            names_pattern = "^(.+)_(q(?:1|2|3))$",
            names_to = c("Infection",".value")),
        dplyr::join_by("Infection"))) |>
  dplyr::mutate(
    Infection = factor(
      .data$Infection,
      levels = c("cvc_ass_bsi","pvc_ass_bsi","vs_ass_hap","inv_ass_hap",
                 "niv_ass_hap"))) |>
  dplyr::arrange(Infection)

surgeries <- data$surgeryData |>
  dplyr::mutate(group = get_procedure_category(main_procedure_code)) |>
  dplyr::filter(group != "not_surgery") |>
  dplyr::inner_join(
    data$events |>
      dplyr::select(event_key, patient_key),
    dplyr::join_by(event_key))

n_procedures <- nrow(surgeries)
n_operated_patients <- surgeries |>
  dplyr::pull(patient_key) |>
  unique() |>
  length()

table_surgery_rates <- tibble::tibble(
  group = "overall",
  n_procedures = n_procedures,
  procedure_rate = n_procedures / n_enrolled_patients * 100) |> 
  bind_cols(
    department_patients |>
      dplyr::select(!"n_enrollments") |>
      dplyr::left_join(
        surgeries |>
          inner_join(data$events, join_by(event_key)) |>
          dplyr::group_by(department_key) |>
          dplyr::summarise(n_procedures = n()),
        dplyr::join_by(department_key)) |>
      dplyr::mutate(
        procedure_rate = tidyr::replace_na(n_procedures, 0) / n_patients * 100,
        .keep = "unused") |>
      dplyr::pull(procedure_rate) |>
      quantile(prob = c(.25,.5,.75)) |>
      tibble::tibble(name = c("q1","q2","q3")) |>
      pivot_wider(values_from = "quantile(...)")) |>
  bind_rows(
    surgeries |>
      dplyr::group_by(group) |>
      dplyr::summarise(n_procedures = dplyr::n()) |>
      dplyr::mutate(procedure_rate = n_procedures / n_enrolled_patients * 100) |>
      dplyr::inner_join(
        data$enrollments |>
          dplyr::group_by(department_key) |>
          dplyr::summarise(n_patients = dplyr::n_distinct(patient_key)) |>
          dplyr::left_join(
            data$events |>
              dplyr::inner_join(
                surgeries,
                dplyr::join_by(event_key)) |>
              dplyr::group_by(department_key, group) |>
              dplyr::summarise(n_procedures = dplyr::n(), .groups = "drop"),
            dplyr::join_by(department_key)) |>
          dplyr::mutate(rate = n_procedures / n_patients * 100, .keep = "unused") |>
          tidyr::pivot_wider(
            names_from = "group",
            values_from = "rate",
            values_fill = 0) |>
          dplyr::select(!c("NA","department_key")) |>
          dplyr::reframe(dplyr::across(tidyselect::everything(), ~quantile(.x, prob = c(.25,.5,.75)))) |>
          dplyr::bind_cols(tibble::tibble(Q = c("q1","q2","q3"))) |>
          tidyr::pivot_longer(!"Q", names_to = "group") |>
          tidyr::pivot_wider(names_from = Q),
        dplyr::join_by(group)) |>
      dplyr::mutate(group = factor(
        group,
        levels = c(
          "overall",
          "abdominal_surgery",
          "neurosurgery",
          "inguinal_hernia_surgery",
          "cardiac_and_large_vessel_surgery",
          "lung_pleural_space_thoracic_surgery",
          "other"))) |>
      dplyr::arrange(group))

```
