---
title: "NeoIPC Reference Report"
lang: en
format: html
echo: false
execute:
  keep-md: true
params:
  reportingPeriodFrom: NULL
  reportingPeriodTo: NULL
  birthWeightFrom: NULL
  birthWeightTo: NULL
  gestationalAgeFrom: NULL
  gestationalAgeTo: NULL
  countryFilter: NULL
  hospitalFilter: NULL
  testUnitFilter: true
  defaultPatientFilter: true
  token: NULL
---

```{r Pre-Setup}
locale = "en"
options(OutDec = ",", gt.locale = locale)
invisible(Sys.setlocale(category = "LC_ALL", locale = "en_GB.utf8"))
trnsl <- list(
  multipleBirthCategories = list(
    singleBirth = "Single birth",
    twins = "Twins",
    tripletsOrMore = "Triplet or more"
  ),
  headerList = list(
    createdAt = "Created",
    analysisPeriod = "Analysis period",
    country = "Country",
    countries = "Countries",
    birthweightFilter = "Birth weight filter",
    allBirthweights = "All birth weights",
    gestationalAgeFilter = "Gestational age filter",
    allGestationalAges = "All gestational ages",
    multiCountryHintHeader = "Multinational analysis",
    multiCountryHint = "This report aggregates data from neonatal units in several countries. This means that, while it reflects a broad spectrum of care structures, it is only suitable as a benchmark to a somewhat limited extent due to the sometimes very different healthcare systems and the resources available there.",
    multiCountryHintGoal = "The aim of NeoIPC Surveillance is therefore always to provide a national or regional report, provided that a sufficient number of units in the respective region participate in the system.",
    singleCountryHintHeader = "National report",
    singleCountryHint = "This report presents data from neonatal units in a single country. This means that, because of the relative homogeneity of the healthcare system, it is in principle a good benchmark. However, it should be noted that only a proportion of neonatal units in a country actually participate in NeoIPC Surveillance. Since participation is voluntary, these are typically hospitals that have a particular interest in infection prevention and are willing and able to provide the resources required for surveillance.",
    singleCountryRepresentativenessHint = "The information presented here can therefore not fully describe the situation in the individual countries.",
    specialAnalysisHint = "This is a special analysis that",
    includesTestDepartments = "includes test units",
    and = " and ",
    ignoresInclusionCriteria = "ignores the NeoIPC Surveillance inclusion criteria."
  ),
  pats = list(
    all = "Number of all patients",
    days = "Sum of all patient days"
  ),
  devs = list(
    VC = list(
      days = "Vascular-Catheter Utilisation Duration",
      days.abbr = "Vasc.-cath. days",
      pats = "Patients With Vascular Cathteters",
      pats.abbr = "Pat. w. vasc. cath.",
      rate = "Vascular-catheter utilisation rate",
      density_rate = "Vascular-catheter utilisation density rate",
      CVC = list(
        name = "CVC",
        rate = "CVC utilisation rate",
        density_rate = "CVC utilisation density rate",
        pats.no = "Number of patients with CVC",
        days.sum = "Sum of CVC Days"
      ),
      PVC = list(
        name = "PVC",
        rate = "PVC utilisation rate",
        density_rate = "PVC utilisation density rate",
        pats.no = "Number of patients with PVC",
        days.sum = "Sum of PVC Days"
      )
    ),
    VS = list(
      days = "Vent.-supp. days",
      pats = "Pat. w. vent. supp.",
      NIV = list(
        name = "NIV"
      ),
      INV = list(
        name = "INV"
      )
    )
  ),
  globalTable = list(
    PooledMean = "Pooled mean",
    Q1 = "Q1",
    Median = "Median",
    Q3 = "Q3"
  ),
  sepsisTable = list(
    Header = "Sepsis/Meningitis",
    PathogenSource = "Source of pathogen detection",
    Definition = "Definition",
    IncidenceRate = "Incidence density rate",
    NoOfInfections = "No. of infections",
    Q1 = "Q1",
    Median = "Median",
    Q3 = "Q3",
    Total = "Total",
    Pathogens = "Non-commensals",
    Commensals = "Commensals",
    Clinical = "Clinical sepsis",
    CsfPositive = "CSF",
    NumberOfInfections = "Number of infections",
    SumOfPatientDays = "Sum of patient days"
  ),
  vcSepsisTable = list(
    Header = "Vascular-Catheter-Associated Sepsis",
    VcAssociation = "Vascular-catheter association",
    vcAssociatedIncidenceRate = "Vascular-catheter-associated sepsis rate",
    CvcAssociated = "CVC-associated",
    PvcAssociated = "PVC-associated",
    CvcAssociatedIncidenceRate = "CVC-associated sepsis rate",
    NumberOfCvcAssociatedInfections = "Number of CVC-associated sepsis cases",
    SumOfCvcDays = "Sum of CVC-days",
    PvcAssociatedIncidenceRate = "PVC-associated sepsis rate",
    NumberOfPvcAssociatedInfections = "Number of PVC-associated sepsis cases",
    SumOfPvcDays = "Sum of PVC-days"
  )
)
```

{{< include _setup.qmd >}}

{{< include _header.qmd >}}

## Introduction

This is the [NeoIPC Surveillance](https://neoipc.org/surveillance/ "Link to the surveillance section of the NeoIPC website") reference analysis that you can use to assess infection rates in your neonatal unit. If you have your own data collected using the same or a comparable method, you can compare them with the reference values presented in this document and identify any anomalies and potential for improvement.

To enable institutions with limited resources to carry out continuous surveillance and to allow benchmarking against a comparable group of patients, NeoIPC surveillance is limited to high-risk neonates and selected risk factors and infections. Further details can be found in the [NeoIPC Surveillanceprotokoll](https://neoipc.org/wp-content/uploads/2023/08/NeoIPC-Surveillance_Core-Module-Protocol.pdf "Link to the NeoIPC surveillance protocol (pdf, English)").

Taking into account the filtering criteria mentioned above, and thanks to the active cooperation of the departments involved in NeoIPC surveillance, this report includes the complete data sets of a total of *`{r} fn(totPat)` patients* from *`{r} fn(totEnr)` stays* in *`{r} fn(totDept)` departments* with a total of *`{r} fn(totPatDay)` days of surveillance*. The data of a further *`{r} fn(totIncPat)` patients* who were still under active surveillance at the time of the data analysis and who therefore could not yet be analysed, will be available for this analysis as soon as their surveillance has been completed.

### General remarks

The following values are repeated in the reference tables for each indicator:

Pooled arithmetic mean:

:   This is calculated by adding the respective numerator across all departments and then dividing by the denominator, which is also added across all departments. The whole data set is thus treated as a single neonatal department by pooling the data from the individual departments.

Quartiles:

:    To calculate the quartiles, the corresponding rate is first calculated for all units in the data set, and then the quantiles are calculated for the determined rates at p = 0.25, p = 0.5 and p = 0.75.
    
    Q1:
    
    : The first quartile separates the quarter of departments with the lowest values of the respective rate from the three quarters with higher values.
    
    Median:
    
    : The median separates the half of the departments with the lower values of the respective rate from the half with the higher values.
    
    Q3:
    
    : The third quartile separates the quarter of departments with the highest values of the respective rate from the three quarters with lower values.

### Primary Sepsis / Bloodstream Infection

Primary sepsis is the most common and most important nosocomial infection in neonatology. However, in clinical practice, diagnosis is not trivial because the usual way to achieve sensitive diagnostics, namely the inoculation of several blood culture bottles with a sufficient amount of blood, is often blocked and contamination of the samples can easily occur due to the complex blood collection process. To enable sensitive and specific surveillance in the face of these diagnostic challenges, NeoIPC surveillance uses a number of sub-definitions to avoid the misclassification of contamination and to enable the detection of sepsis cases even when blood culture results are negative or unavailable. Meningitis, which in neonatology is almost always hematogenous in origin unless associated with a surgical procedure, is also presented in this section as a complication of sepsis.

{{< include _sepsis-table.qmd >}}

#### The Vascular Catheter as a Risk Factor for Sepsis

{{< include _vc-application-rate-table.qmd >}}

{{< include _vc-application-density-rate-table.qmd >}}

{{< include _vc-sepsis-table.qmd >}}

### Infections of the Lower Respiratory Tract / Pneumonia

TODO: Inzidenzdichte der UAWIs

#### Atemunterstützung als Risikofaktor für Atemwegsinfektionen

TODO: Expositions- und Anwendungsraten für INV und NIV sowie Beatmungsassoziierte UAWIs

### Schwere Infektion

TODO: Inzidenz und Inzidenzdichte schwerer Infektionen und SIR

### Nekrotisierende Enterokolitis

### Infektionserreger

#### Multiresistente Erreger
