---
title: "NeoIPC Surveillance Referenzauswertung"
lang: de
format: html
echo: false
execute:
  keep-md: true
params:
  reportingPeriodFrom: NULL
  reportingPeriodTo: NULL
  birthWeightFrom: NULL
  birthWeightTo: NULL
  gestationalAgeFrom: NULL
  gestationalAgeTo: NULL
  countryFilter: NULL
  hospitalFilter: NULL
  testUnitFilter: true
  defaultPatientFilter: true
  token: NULL
---

{{< include _pre-setup.de.qmd >}}

{{< include _setup.qmd >}}

{{< include _header.qmd >}}

## Einführung

Dies ist die Referenzauswertung der [NeoIPC Surveillance](https://neoipc.org/surveillance/ "Link zum Surveillance-Bereich der NeoIPC Website"), die Sie verwenden können, um die Infektionsraten Ihrer neonatologischen Abteilung zu bewerten. Wenn Sie über eigene Vergleichsdaten verfügen, die mit der selben oder einer vergleichbaren Methode erhoben wurden, können Sie diese mit den in diesem Dokument dargestellten Referenzwerten vergleichen und gegebenenfalls Auffälligkeiten und Verbesserungspotenziale identifizieren.

Um auch Einrichtungen mit geringen Ressourcen eine kontinuierliche Surveillance zu ermöglichen und um ein Benchmarking anhand einer vergleichbaren Patientengruppe durchführen zu können, beschränkt sich die NeoIPC Surveillance auf neonatologische Hochrisikopatienten sowie auf ausgewählte Risikofaktoren und Infektionen. Details dazu finden Sie bei Bedarf im [NeoIPC Surveillanceprotokoll](https://neoipc.org/wp-content/uploads/2023/08/NeoIPC-Surveillance_Core-Module-Protocol.pdf "Link zum NeoIPC Surveillanceprotokoll (pdf, englisch)").

Unter Berücksichtigung der oben angegebenen Filterkriterien umfasst diese Auswertung dank der aktiven Mitarbeit der an der NeoIPC Surveillance beteiligten Abteilungen die vollständigen Datensätze von insgesamt *`{r} fn(totPat)` Patienten* aus *`{r} fn(totEnr)` Aufenthalten* in *`{r} fn(totDept)` Abteilungen* mit insgesamt *`{r} fn(totPatDay)` Tagen unter Surveillance*. Die Daten weiterer *`{r} fn(totIncPat)` Patienten*, die sich zum Auswertungszeitpunkt noch in der aktiven Surveillance befinden und daher noch nicht ausgewertet werden können, werden für diese Auswertung zur Verfügung stehen, sobald die Surveillance bei ihnen jeweils abgeschlossen ist.

## Beschreibung der Population und ihrer Risikofaktoren

Wenn wir aus Sicht der Infektionsprävention von Hochrisikopatienten sprechen, meinen wir, dass es bei diesen Patienten Merkmale gibt, die das Infektionsrisiko erhöhen. Dabei kann es sich sowohl um unveränderliche patienteneigene Merkmale handeln als auch um mehr oder weniger beeinflussbare Merkmale, die sich aus der oft komplexen Behandlung dieser Patienten ergeben.

Wenn wir diese Merkmale epidemiologisch beobachten, nennen wir sie oft Risikofaktoren und manchmal auch Schutzfaktoren (protektive Faktoren), was dann als Umkehrung eines Risikofaktors angesehen wird. Dies ist jedoch überflüssig, da der Begriff Risikofaktor eigentlich nur aussagt, dass dieses Merkmal das Risiko beeinflusst (erhöht oder verringert).

Bei neonatologischen Patienten sind z. B. die Dauer der Schwangerschaft bis zur Geburt (Gestationsalter), das Körpergewicht bei der Geburt (Geburtsgewicht), aber auch das Alter nach der Geburt (postnatales Alter) prominente patienteneigene Merkmale, die das Risiko, eine Infektion zu entwickeln, beeinflussen (dispositionelle Risikofaktoren).

Beispiele für in gewissen Grenzen beeinflussbare Merkmale, die sich ebenfalls auf das Infektionsrisiko auswirken können (expositionelle Risikofaktoren), sind dagegen Gefäßzugänge, Beatmung und Ernährung mit Muttermilch sowie die Dauer, während der diese Merkmale vorhanden sind.

Im Folgenden werden die im Rahmen der NeoIPC Surveillance beobachteten Risikofaktoren und ihre Verteilung in den am System beteiligten Partnerabteilungen dargestellt, wobei die expositionellen Risikofaktoren möglicherweise helfen können, die Prozesse in der eigenen Abteilung (z.B. Indikationsstellung für Therapien) zu beurteilen, während die dispositionellen Risikofaktoren eher geeignet sind, die Vergleichbarkeit der eigenen Patientenpopulation mit der Population in der NeoIPC Referenzdatenbank zu beurteilen. Je mehr die Zusammensetzung der Patientenpopulation die Sie mit den in der NeoIPC Surveillance Referenzauswertung dargestellten Raten vergleichen möchten, sich im Hinblick auf die gezeigten Merkmale unterscheidt, desto eingeschränkter ist ein Benchmarking möglich. Unterschiede und ihre möglichen Auswirkungen müssen bei der Interpretation stets sorgfältig berücksichtgt werden.

### Gestationsalter

{{< include _ga-figure.qmd >}}

### Geburtsgewicht

{{< include _bw-figure.qmd >}}

### Aufnahmezeitpunkt und Verweildauer

{{< include _surveillance-duration-figure.qmd >}}

ToDo

### Weitere dispositionelle Risikofaktoren

```{r}

sexBarChart <- patients |>
  dplyr::group_by(NEOIPC_TEA_SEX) |>
  dplyr::summarise(percent = n() / nrow(patients)) |>
  #left_join(data$metadata$deliveryModes, join_by("NEOIPC_TEA_SEX" == "code")) |>
  #select(displayName, percent) |>
  ggplot(aes(y = percent, x = NEOIPC_TEA_SEX)) +
  geom_col(position = "dodge") +
  ggtitle(data$metadata$trackedEntityAttributes |>
            filter(code == "NEOIPC_TEA_SEX") |>
            pull(displayName)) +
  scale_y_continuous(labels = label_percent(), limits = c(0.40, 0.60), oob=rescale_none) +
  coord_flip() +
  theme(axis.title = element_blank())

mbBarChart <- patients |>
  dplyr::group_by(multiple_birth_category) |>
  dplyr::summarise(percent = n() / nrow(patients)) |>
  #left_join(data$metadata$deliveryModes, join_by("NEOIPC_TEA_SEX" == "code")) |>
  #select(displayName, percent) |>
  ggplot(aes(y = percent, x = multiple_birth_category)) +
  geom_col(position = "dodge") +
  ggtitle(data$metadata$trackedEntityAttributes |>
            filter(code == "NEOIPC_TEA_SIBLINGS") |>
            pull(displayName)) +
  scale_y_continuous(labels = label_percent()) +
  coord_flip() +
  theme(axis.title = element_blank())

dmBarChart <- patients |>
  dplyr::group_by(NEOIPC_TEA_DELIVERY_MODE) |>
  dplyr::summarise(percent = n() / nrow(patients)) |>
  left_join(data$metadata$deliveryModes, join_by("NEOIPC_TEA_DELIVERY_MODE" == "code")) |>
  select(displayName, percent) |>
  ggplot(aes(y = percent, x = displayName)) +
  geom_col(position = "dodge") +
  ggtitle(data$metadata$trackedEntityAttributes |>
            filter(code == "NEOIPC_TEA_DELIVERY_MODE") |>
            pull(displayName)) +
  scale_y_continuous(labels = label_percent()) +
  coord_flip() +
  theme(axis.title = element_blank())

sexBarChart / mbBarChart / dmBarChart
```

### Faktoren die das Mikrobiom beeinflussen

#### Antbiotikaanwendung

TODO: Expositions- und Anwendungsraten für AWaRE-Klassen, ATC-Substanzgruppen und Einzelsubstanzen

#### Humane Milch und Probiotika

#### Kängugruh-Pflege

## Nosokomiale Infektionen

Da Infektionen in der Neonatologie eine lebensbedrohliche Komplikation darstellen, die selbst bei erfolgreicher Behandlung das Risiko für weitere Komplikationen und Entwicklungsstörungen erhöht, stehen sie im Mittelpunkt der NeoIPC Surveillance, wobei nur solche Infektionsarten erfasst werden, die aufgrund ihrer Häufigkeit ein sinnvolles Benchmarking ermöglichen.

### Primäre Sepsis / Blutstrominfektion

Die primäre Sepsis ist die häufigste und wichtigste nosokomiale Infektion in der Neonatologie. Im klinischen Alltag ist die Diagnose jedoch nicht trivial, da der übliche Weg zu einer sensitiven Diagnostik, nämlich die Beimpfung mehrerer Blutkulturflaschen mit einer ausreichenden Menge Blut, oft versperrt ist und es aufgrund der komplexen Abläufe bei der Blutentnahme leicht zu Kontaminationen der Proben kommen kann. Um angesichts der diagnostischen Herausforderungen eine sensitive und spezifische Surveillance zu ermöglichen, werden bei der NeoIPC-Surveillance mehrere Unterdefinitionen verwendet, um die Erfassung von Kontaminationen zu vermeiden und die Erfassung von Sepsisfällen auch bei negativen oder fehlenden Blutkulturergebnissen zu ermöglichen. Die Meningitis, die in der Neonatologie fast immer hämatogen entsteht, wenn sie nicht mit einem chirurgischen Eingriff verbunden ist, wird als Komplikation der Sepsis ebenfalls in diesem Abschnitt dargestellt.

<!--# Todo: Graph displaying the proportion of the different definitions, maybe even sub-definitions -->

{{< include _sepsis-table.qmd >}}

#### Der Gefäßkatheter als Risikofaktor für Sepsis

{{< include _vc-application-rate-table.qmd >}}

{{< include _vc-application-density-rate-table.qmd >}}

{{< include _vc-sepsis-table.qmd >}}

### Infektionen der unteren Atemwege / Pneumonie

TODO: Inzidenzdichte der UAWIs

#### Atemunterstützung als Risikofaktor für Atemwegsinfektionen

TODO: Expositions- und Anwendungsraten für INV und NIV sowie Beatmungsassoziierte UAWIs

### Schwere Infektion

TODO: Inzidenz und Inzidenzdichte schwerer Infektionen und SIR

### Nekrotisierende Enterokolitis

### Infektionserreger

#### Multiresistente Erreger
