<#
.SYNOPSIS
    Creates a DHIS2 metadata package from source-controlled metadata.

.DESCRIPTION
    Orchestrates the full metadata package creation pipeline:
    1. Executes generators to create repetitive metadata
    2. Merges manual overrides from CSV/YAML files
    3. Applies po4a translations
    4. Assembles final JSON package with dependency resolution

.PARAMETER ProgramCode
    Code of the program to build (e.g., 'neoipc-core'). Defaults to all programs.

.PARAMETER SkipGenerators
    Skip generator execution and use existing _generated content.

.PARAMETER SkipTranslations
    Skip translation application and only include base language.

.PARAMETER IncludeOrganisationUnits
    Include organisation units in the package.

.PARAMETER IncludeSharedData
    Include shared-data dependencies (infectious-agents, antibiotics, etc.).

.PARAMETER OutputPath
    Path where metadata.json should be written. Defaults to ./metadata.json.

.PARAMETER Compress
    Output compressed JSON instead of pretty-printed.

.PARAMETER SemanticVersion
    Semantic version for the package (e.g., '2.3.1'). Required for publication.

.EXAMPLE
    .\Create-MetadataPackage.ps1 -ProgramCode 'neoipc-core' -SemanticVersion '2.4.0'

.NOTES
    Requires NeoIPC-Tools module and powershell-yaml module.
#>

[CmdletBinding()]
param(
    [Parameter()]
    [string]$ProgramCode,
    
    [Parameter()]
    [switch]$SkipGenerators,
    
    [Parameter()]
    [switch]$SkipTranslations,
    
    [Parameter()]
    [switch]$IncludeOrganisationUnits,
    
    [Parameter()]
    [switch]$IncludeSharedData,
    
    [Parameter()]
    [string]$OutputPath = "$PSScriptRoot/metadata.json",
    
    [Parameter()]
    [switch]$Compress,
    
    [Parameter()]
    [string]$SemanticVersion,
    
    # Legacy parameters for backward compatibility
    [switch]$Play,
    [switch]$WithOrganisationUnits
)

# Import required modules
Import-Module "$PSScriptRoot/modules/NeoIPC-Tools/NeoIPC-Tools.psm1" -Force
if (-not (Get-Module powershell-yaml)) {
    throw "powershell-yaml module is required. Install with: Install-Module powershell-yaml"
}

# Resolve paths
$metadataDir = (Resolve-Path -Path "$PSScriptRoot/../metadata").Path
$sharedDataDir = Join-Path $PSScriptRoot "..\shared-data"

# Legacy parameter handling
if ($WithOrganisationUnits) { $IncludeOrganisationUnits = $true }

# Initialize package
$metadata = [ordered]@{}
if ($SemanticVersion) {
    $metadata['package'] = @{
        version = $SemanticVersion
        DHIS2Version = '2.40'
        name = "NeoIPC Surveillance Metadata"
        description = "DHIS2 metadata for NeoIPC Surveillance"
    }
}

Write-Host "Building metadata package..." -ForegroundColor Cyan
if ($ProgramCode) {
    Write-Host "  Programs: $ProgramCode"
} else {
    Write-Host "  Programs: All"
}
Write-Host "  Generators: $(-not $SkipGenerators)"
Write-Host "  Translations: $(-not $SkipTranslations)"
Write-Host "  Organisation Units: $IncludeOrganisationUnits"
Write-Host "  Shared Data: $IncludeSharedData"
Write-Host ""

function Import-Translations {
    <#
    .SYNOPSIS
        Legacy CSV translation importer.
    .DESCRIPTION
        Imports translations from .csv files in the format code,property,translated.
        This function is retained for backward compatibility with existing organisation unit translations.
    #>
    param (
        [string]$LiteralPath,
        [string]$BaseName
    )
    $translationDict = @{}
    $translationFiles = Get-ChildItem -LiteralPath $LiteralPath -Filter "$BaseName.*.csv" -ErrorAction SilentlyContinue
    
    foreach ($tf in $translationFiles) {
        $lang = $tf.Name -replace "$BaseName\.([a-z]{2})\.csv",'$1'
        $translations = Import-Csv -LiteralPath $tf.FullName
        foreach ($t in $translations) {
            if (-not $translationDict.ContainsKey($t.code)) {
                $translationsList = [System.Collections.ArrayList]::new()
                $translationDict[$t.code] = $translationsList
            } else {
                $translationsList = $translationDict[$t.code]
            }
            if ($t.needs_translation -eq 't') {
                $translationsList.Add(@{locale=$lang;property=$t.property;value=$t.translated}) > $null
            }
        }
    }
    return $translationDict
}

function Import-YamlTranslations {
    <#
    .SYNOPSIS
        Imports translations from YAML files generated by po4a.
    .DESCRIPTION
        Reads base YAML file and all language-specific YAML files (*.de.yaml, *.fr.yaml, etc.),
        then builds DHIS2 translations array.
    #>
    param (
        [string]$BaseYamlPath
    )
    
    if (-not (Test-Path $BaseYamlPath)) {
        Write-Warning "Base YAML file not found: $BaseYamlPath"
        return @{}
    }
    
    $baseDir = Split-Path $BaseYamlPath -Parent
    $baseName = [System.IO.Path]::GetFileNameWithoutExtension($BaseYamlPath)
    
    # Load base file
    $baseContent = Get-Content -LiteralPath $BaseYamlPath -Raw | ConvertFrom-Yaml
    
    # Find all translation files
    $translationFiles = Get-ChildItem -LiteralPath $baseDir -Filter "$baseName.*.yaml" -ErrorAction SilentlyContinue
    
    $translationDict = @{}
    
    foreach ($tf in $translationFiles) {
        # Extract language code (e.g., "de" from "data-elements.de.yaml")
        if ($tf.Name -match "$baseName\.([a-z]{2})\.yaml$") {
            $lang = $Matches[1]
            $translatedContent = Get-Content -LiteralPath $tf.FullName -Raw | ConvertFrom-Yaml
            
            # Merge translations using Merge-YamlTranslations helper
            $merged = Merge-YamlTranslations -BaseObjects $baseContent -TranslatedObjects $translatedContent -Language $lang
            
            # Build translation dictionary
            foreach ($obj in $merged) {
                if (-not $translationDict.ContainsKey($obj.code)) {
                    $translationDict[$obj.code] = [System.Collections.ArrayList]::new()
                }
                
                # Add translations from this language
                if ($obj.translations) {
                    foreach ($trans in $obj.translations) {
                        if ($trans.locale -eq $lang) {
                            $translationDict[$obj.code].Add($trans) > $null
                        }
                    }
                }
            }
        }
    }
    
    return $translationDict
}

function Import-OrganisationUnits {
    <#
    .SYNOPSIS
        Imports organisation units from CSV with translations.
    #>
    param (
        [string]$LiteralPath,
        [hashtable]$Translations
    )
    $ouList = [System.Collections.ArrayList]::new()
    
    if (-not (Test-Path $LiteralPath)) {
        Write-Warning "Organisation units file not found: $LiteralPath"
        return $ouList.ToArray()
    }
    
    $organisationUnits = Import-Csv -LiteralPath $LiteralPath
    foreach ($organisationUnit in $organisationUnits) {
        $ou = @{}
        $ou.code = $organisationUnit.code
        $ou.name = $organisationUnit.name
        $ou.shortName = $organisationUnit.shortName
        $ou.openingDate = $organisationUnit.openingDate
        if ($Translations.ContainsKey($organisationUnit.code)) {
            $ou.translations = $Translations[$organisationUnit.code].ToArray()
        }
        if ($organisationUnit.parent_code) {
            $ou.parent = @{ code = $organisationUnit.parent_code }
        }
        $ouList.Add($ou) > $null
    }
    return $ouList.ToArray()
}

function Import-MetadataObjects {
    <#
    .SYNOPSIS
        Imports metadata objects from YAML+CSV files.
    .DESCRIPTION
        Reads YAML for translatable content and CSV for technical properties,
        then merges them into DHIS2-compatible objects.
    #>
    param (
        [string]$YamlPath,
        [string]$CsvPath,
        [hashtable]$Translations = @{}
    )
    
    $objects = [System.Collections.ArrayList]::new()
    
    # Load YAML (translatable content)
    $yamlObjects = @{}
    if (Test-Path $YamlPath) {
        $yamlContent = Get-Content -LiteralPath $YamlPath -Raw | ConvertFrom-Yaml
        foreach ($obj in $yamlContent) {
            $yamlObjects[$obj.code] = $obj
        }
    }
    
    # Load CSV (technical properties)
    if (Test-Path $CsvPath) {
        $csvObjects = Import-Csv -LiteralPath $CsvPath
        
        foreach ($csvObj in $csvObjects) {
            $merged = @{
                code = $csvObj.code
            }
            
            # Merge YAML translatable fields
            if ($yamlObjects.ContainsKey($csvObj.code)) {
                $yamlObj = $yamlObjects[$csvObj.code]
                foreach ($key in @('name', 'description', 'formName', 'content')) {
                    if ($yamlObj.ContainsKey($key)) {
                        $merged[$key] = $yamlObj[$key]
                    }
                }
            }
            
            # Merge CSV technical fields
            foreach ($prop in $csvObj.PSObject.Properties) {
                if ($prop.Name -ne 'code' -and ![string]::IsNullOrWhiteSpace($prop.Value)) {
                    # Handle boolean conversion
                    if ($prop.Value -eq 'true') {
                        $merged[$prop.Name] = $true
                    } elseif ($prop.Value -eq 'false') {
                        $merged[$prop.Name] = $false
                    } else {
                        $merged[$prop.Name] = $prop.Value
                    }
                }
            }
            
            # Add translations if available
            if ($Translations.ContainsKey($csvObj.code)) {
                $merged.translations = $Translations[$csvObj.code].ToArray()
            }
            
            $objects.Add($merged) > $null
        }
    }
    
    return $objects.ToArray()
}

function Invoke-Generators {
    <#
    .SYNOPSIS
        Executes all generators for a program.
    #>
    param (
        [string]$ProgramPath
    )
    
    $generatorsConfigPath = Join-Path $ProgramPath "generators\generators.json"
    if (-not (Test-Path $generatorsConfigPath)) {
        Write-Verbose "No generators.json found in $ProgramPath"
        return
    }
    
    Write-Host "  Executing generators..." -ForegroundColor Yellow
    
    $generatorsConfig = Get-Content -LiteralPath $generatorsConfigPath -Raw | ConvertFrom-Json
    
    foreach ($generator in $generatorsConfig.generators) {
        Write-Host "    - $($generator.name)" -ForegroundColor Gray
        
        $result = Invoke-MetadataGenerator `
            -GeneratorScript (Join-Path $ProgramPath "generators\$($generator.script)") `
            -Parameters $generator.parameters `
            -OutputPath (Join-Path $ProgramPath "_generated")
        
        if ($result) {
            Write-Verbose "      Generated $($result.Summary)"
        }
    }
}

# ===== Main Pipeline =====

# Step 1: Execute generators
if (-not $SkipGenerators) {
    Write-Host "`nStep 1: Executing generators" -ForegroundColor Cyan
    
    if ($ProgramCode) {
        $programPath = Join-Path $metadataDir "programs\$ProgramCode"
        Invoke-Generators -ProgramPath $programPath
    } else {
        $programsPath = Join-Path $metadataDir "programs"
        foreach ($programDir in (Get-ChildItem -LiteralPath $programsPath -Directory)) {
            Write-Host "  Program: $($programDir.Name)" -ForegroundColor Yellow
            Invoke-Generators -ProgramPath $programDir.FullName
        }
    }
} else {
    Write-Host "`nStep 1: Skipping generators (using existing _generated content)" -ForegroundColor Gray
}

# Step 2: Import shared data dependencies
if ($IncludeSharedData) {
    Write-Host "`nStep 2: Importing shared data" -ForegroundColor Cyan
    
    # Load dependency manifest
    $depsPath = Join-Path $metadataDir "metadata-dependencies.json"
    if (Test-Path $depsPath) {
        $dependencies = Get-Content -LiteralPath $depsPath -Raw | ConvertFrom-Json
        
        foreach ($dep in $dependencies.dependencies) {
            Write-Host "  - $($dep.domain) v$($dep.version)" -ForegroundColor Gray
            
            $domainPath = Join-Path $sharedDataDir $dep.domain
            if (Test-Path $domainPath) {
                # Import option sets
                $optionSetsYaml = Join-Path $domainPath "optionSets.yaml"
                $optionSetsCsv = Join-Path $domainPath "optionSets.csv"
                
                $translations = @{}
                if (-not $SkipTranslations) {
                    $translations = Import-YamlTranslations -BaseYamlPath $optionSetsYaml
                }
                
                $optionSets = Import-MetadataObjects `
                    -YamlPath $optionSetsYaml `
                    -CsvPath $optionSetsCsv `
                    -Translations $translations
                
                if ($optionSets.Count -gt 0) {
                    if (-not $metadata.ContainsKey('optionSets')) {
                        $metadata['optionSets'] = [System.Collections.ArrayList]::new()
                    }
                    $metadata['optionSets'].AddRange($optionSets)
                }
                
                # Import options
                $optionsYaml = Join-Path $domainPath "options.yaml"
                $optionsCsv = Join-Path $domainPath "options.csv"
                
                $optionTranslations = @{}
                if (-not $SkipTranslations) {
                    $optionTranslations = Import-YamlTranslations -BaseYamlPath $optionsYaml
                }
                
                $options = Import-MetadataObjects `
                    -YamlPath $optionsYaml `
                    -CsvPath $optionsCsv `
                    -Translations $optionTranslations
                
                if ($options.Count -gt 0) {
                    if (-not $metadata.ContainsKey('options')) {
                        $metadata['options'] = [System.Collections.ArrayList]::new()
                    }
                    $metadata['options'].AddRange($options)
                }
            } else {
                Write-Warning "Shared data directory not found: $domainPath"
            }
        }
    } else {
        Write-Warning "No metadata-dependencies.json found"
    }
}

# Step 3: Import program metadata
Write-Host "`nStep 3: Importing program metadata" -ForegroundColor Cyan

$programsToImport = @()
if ($ProgramCode) {
    $programsToImport += $ProgramCode
} else {
    $programsPath = Join-Path $metadataDir "programs"
    $programsToImport = (Get-ChildItem -LiteralPath $programsPath -Directory).Name
}

foreach ($progCode in $programsToImport) {
    Write-Host "  Program: $progCode" -ForegroundColor Yellow
    $programPath = Join-Path $metadataDir "programs\$progCode"
    
    # Import metadata types: data elements, tracked entity attributes, programs, etc.
    $metadataTypes = @(
        @{ type = 'dataElements'; subdir = 'data-elements' },
        @{ type = 'trackedEntityAttributes'; subdir = 'tracked-entity-attributes' },
        @{ type = 'programStages'; subdir = 'stages' },
        @{ type = 'programRules'; subdir = 'rules' },
        @{ type = 'programRuleVariables'; subdir = 'rules/variables' }
    )
    
    foreach ($metaType in $metadataTypes) {
        # Check manual directory
        $manualDir = Join-Path $programPath $metaType.subdir
        $generatedDir = Join-Path $programPath "_generated\$($metaType.subdir)"
        
        $allObjects = [System.Collections.ArrayList]::new()
        
        # Import from _generated first
        if ((Test-Path $generatedDir) -and (-not $SkipGenerators)) {
            foreach ($yamlFile in (Get-ChildItem -LiteralPath $generatedDir -Filter "*.yaml" -ErrorAction SilentlyContinue)) {
                $csvFile = $yamlFile.FullName -replace '\.yaml$', '.csv'
                
                $translations = @{}
                if (-not $SkipTranslations) {
                    $translations = Import-YamlTranslations -BaseYamlPath $yamlFile.FullName
                }
                
                $objects = Import-MetadataObjects `
                    -YamlPath $yamlFile.FullName `
                    -CsvPath $csvFile `
                    -Translations $translations
                
                $allObjects.AddRange($objects)
            }
        }
        
        # Import from manual directory (overrides generated)
        if (Test-Path $manualDir) {
            foreach ($yamlFile in (Get-ChildItem -LiteralPath $manualDir -Filter "*.yaml" -ErrorAction SilentlyContinue)) {
                $csvFile = $yamlFile.FullName -replace '\.yaml$', '.csv'
                
                $translations = @{}
                if (-not $SkipTranslations) {
                    $translations = Import-YamlTranslations -BaseYamlPath $yamlFile.FullName
                }
                
                $objects = Import-MetadataObjects `
                    -YamlPath $yamlFile.FullName `
                    -CsvPath $csvFile `
                    -Translations $translations
                
                # Merge with generated (manual overrides)
                foreach ($obj in $objects) {
                    $existing = $allObjects | Where-Object { $_.code -eq $obj.code } | Select-Object -First 1
                    if ($existing) {
                        # Replace with manual version
                        $index = $allObjects.IndexOf($existing)
                        $allObjects[$index] = $obj
                        Write-Verbose "    Manual override: $($obj.code)"
                    } else {
                        $allObjects.Add($obj) > $null
                    }
                }
            }
        }
        
        if ($allObjects.Count -gt 0) {
            Write-Host "    - $($metaType.type): $($allObjects.Count) objects" -ForegroundColor Gray
            $metadata[$metaType.type] = $allObjects.ToArray()
        }
    }
}

# Step 4: Import organisation units (legacy)
if ($IncludeOrganisationUnits) {
    Write-Host "`nStep 4: Importing organisation units" -ForegroundColor Cyan
    
    $ouPath = "$metadataDir/common/organisation_units"
    if (Test-Path $ouPath) {
        $translationDict = Import-Translations -LiteralPath $ouPath -BaseName 'organisationUnits'
        $ouList = @(Import-OrganisationUnits -LiteralPath "$ouPath/organisationUnits.csv" -Translations $translationDict)
        
        if ($Play) {
            $playPath = "$metadataDir/play"
            if (Test-Path $playPath) {
                $translationDict = Import-Translations -LiteralPath $playPath -BaseName 'organisationUnits'
                $ouList += @(Import-OrganisationUnits -LiteralPath "$playPath/organisationUnits.csv" -Translations $translationDict)
            }
        }
        
        if ($ouList.Count -gt 0) {
            Write-Host "  - $($ouList.Count) organisation units" -ForegroundColor Gray
            $metadata['organisationUnits'] = $ouList
        }
    }
}

# Step 5: Write package

# Step 5: Write package
Write-Host "`nStep 5: Writing package to $OutputPath" -ForegroundColor Cyan

$jsonOutput = ConvertTo-Json -InputObject $metadata -Depth 100 -Compress:$Compress.IsPresent

# Calculate statistics
$stats = @{}
foreach ($key in $metadata.Keys) {
    if ($metadata[$key] -is [System.Collections.ICollection]) {
        $stats[$key] = $metadata[$key].Count
    }
}

Write-Host "`nPackage Statistics:" -ForegroundColor Green
foreach ($key in ($stats.Keys | Sort-Object)) {
    Write-Host "  $key: $($stats[$key])" -ForegroundColor Gray
}

# Write to file
$jsonOutput | Out-File -LiteralPath $OutputPath -Encoding utf8NoBOM -Force

Write-Host "`nPackage created successfully!" -ForegroundColor Green
Write-Host "Output: $OutputPath" -ForegroundColor Cyan
Write-Host "Size: $([math]::Round((Get-Item $OutputPath).Length / 1KB, 2)) KB" -ForegroundColor Gray
