name: Build

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
    build-docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Prepare environment
              shell: bash
              run: |
                sudo apt-get update -qq
                sudo apt-get install -qq pandoc librsvg2-bin fnt
                sudo gem install asciidoctor-pdf
                gem install asciimath
                sudo fnt update
                sudo fnt install notosans

            - name: Build
              shell: pwsh
              run: ./doc/build.ps1 -InformationAction Continue

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                name: NeoIPC-Docs-Preview
                path: ./doc/out/
